baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Example site with author pages"

# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[taxonomies]
  author = "authors"
  tag = "tags"
